In [40]:
import pandas as pd
df = pd.read_csv("FinalAddedFeatures30sec.csv").dropna()

In [41]:
df.head()

src            dst  sport  dport  proto  smallpacket  \
1    172.16.0.12   64.95.58.150   1036     80      6            3   
2   64.95.58.150    172.16.0.12     80   1036      6            4   
3    172.16.0.12     89.3.63.62   1038     80      6            3   
4     89.3.63.62    172.16.0.12     80   1038      6            4   
34   172.16.0.11  84.16.239.110  22252  12394     17            2   

    packetratio  initlen   Botresp  label   outavglen    inavglen  averagelen  \
1      0.411765       48  0.708333      1  519.411765  611.571429  546.291667   
2      0.739130       48  0.575000      0  567.956522  519.411765  547.325000   
3      0.363636       48  0.733333      1  195.272727  177.750000  190.600000   
4      0.785714       48  0.560000      0  200.785714  195.272727  198.360000   
34     0.875000       53  0.533333      1   50.375000   96.571429   71.933333   

        outvarlen       invarlen      totavglen  noofpackets  
1   400162.830450  445105.102041  415025.706597           24  
2   421805.519849  400162.830450  413183.269375           40  
3    89316.743802   54753.187500   80159.840000           15  
4    84329.311224   89316.743802   86531.270400           25  
34      48.234375   26062.530612   12719.395556           15

In [42]:
df_packet = df.drop(['src','dst','sport','dport'],1)

In [43]:
df_packet.head()

proto  smallpacket  packetratio  initlen   Botresp  label   outavglen  \
1       6            3     0.411765       48  0.708333      1  519.411765   
2       6            4     0.739130       48  0.575000      0  567.956522   
3       6            3     0.363636       48  0.733333      1  195.272727   
4       6            4     0.785714       48  0.560000      0  200.785714   
34     17            2     0.875000       53  0.533333      1   50.375000   

      inavglen  averagelen      outvarlen       invarlen      totavglen  \
1   611.571429  546.291667  400162.830450  445105.102041  415025.706597   
2   519.411765  547.325000  421805.519849  400162.830450  413183.269375   
3   177.750000  190.600000   89316.743802   54753.187500   80159.840000   
4   195.272727  198.360000   84329.311224   89316.743802   86531.270400   
34   96.571429   71.933333      48.234375   26062.530612   12719.395556   

    noofpackets  
1            24  
2            40  
3            15  
4            25  
34           15

In [44]:
df_packet.columns

Index(['proto', 'smallpacket', 'packetratio', 'initlen', 'Botresp', 'label',
       'outavglen', 'inavglen', 'averagelen', 'outvarlen', 'invarlen',
       'totavglen', 'noofpackets'],
      dtype='object')

In [45]:
df_packet_unique =  df_packet.drop_duplicates(subset=['smallpacket','packetratio','initlen','Botresp'])

In [46]:
print(df_packet_unique.shape)
print(df_packet.shape)

(4652, 13)
(113288, 13)


In [47]:
df_packet_unique.drop(['proto'],1).corr()

smallpacket  packetratio   initlen   Botresp     label  \
smallpacket     1.000000     0.009811  0.019967 -0.005157 -0.043916   
packetratio     0.009811     1.000000  0.009090 -0.758952  0.036644   
initlen         0.019967     0.009090  1.000000 -0.025248  0.020887   
Botresp        -0.005157    -0.758952 -0.025248  1.000000  0.089758   
label          -0.043916     0.036644  0.020887  0.089758  1.000000   
outavglen       0.044234    -0.135156 -0.039826  0.098973 -0.252840   
inavglen        0.025813    -0.136577 -0.045890  0.124915 -0.111571   
averagelen      0.052336    -0.140516 -0.041440  0.106209 -0.205961   
outvarlen      -0.010778    -0.174763 -0.086254  0.168022 -0.217045   
invarlen       -0.022057    -0.140970 -0.077768  0.120227 -0.228934   
totavglen       0.038680    -0.140038 -0.074023  0.108995 -0.223905   
noofpackets     0.518464    -0.002248 -0.007239 -0.015693 -0.047615   

             outavglen  inavglen  averagelen  outvarlen  invarlen  totavglen  \
smallpacket   0.044234  0.025813    0.052336  -0.010778 -0.022057   0.038680   
packetratio  -0.135156 -0.136577   -0.140516  -0.174763 -0.140970  -0.140038   
initlen      -0.039826 -0.045890   -0.041440  -0.086254 -0.077768  -0.074023   
Botresp       0.098973  0.124915    0.106209   0.168022  0.120227   0.108995   
label        -0.252840 -0.111571   -0.205961  -0.217045 -0.228934  -0.223905   
outavglen     1.000000  0.662226    0.907180   0.848469  0.745937   0.866816   
inavglen      0.662226  1.000000    0.905669   0.782819  0.708694   0.847989   
averagelen    0.907180  0.905669    1.000000   0.879763  0.793192   0.951695   
outvarlen     0.848469  0.782819    0.879763   1.000000  0.871126   0.916657   
invarlen      0.745937  0.708694    0.793192   0.871126  1.000000   0.868969   
totavglen     0.866816  0.847989    0.951695   0.916657  0.868969   1.000000   
noofpackets   0.190969  0.162314    0.214884   0.078877  0.054892   0.174389   

             noofpackets  
smallpacket     0.518464  
packetratio    -0.002248  
initlen        -0.007239  
Botresp        -0.015693  
label          -0.047615  
outavglen       0.190969  
inavglen        0.162314  
averagelen      0.214884  
outvarlen       0.078877  
invarlen        0.054892  
totavglen       0.174389  
noofpackets     1.000000

In [48]:
from sklearn import feature_selection
feature_selection.chi2(df_packet_unique.drop(['proto','label'],1),df_packet_unique['label'].astype('int'))

(array([4.37893094e+03, 5.31033345e+00, 4.84200862e+01, 1.25020470e+00,
        1.06701431e+05, 2.69131015e+04, 6.69228834e+04, 6.65737524e+07,
        6.94741979e+07, 6.92107316e+07, 9.33387107e+04]),
 array([0.00000000e+00, 2.11992985e-02, 3.44026310e-12, 2.63513384e-01,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]))

In [49]:
from sklearn.feature_selection import SelectKBest,f_classif
X,y = (df_packet_unique.drop(['proto','label'],1),df_packet_unique['label'].astype('int'))
SelectKBest(f_classif,k='all').fit(X,y).score_func(X,y)

(array([  8.98556973,   6.25217674,   2.02960884,  37.7670422 ,
        317.56670491,  58.61277844, 205.9907166 , 229.88348812,
        257.18871271, 245.42384596,  10.56627108]),
 array([2.73558698e-03, 1.24382367e-02, 1.54327414e-01, 8.63802409e-10,
        9.07786245e-69, 2.31990538e-14, 9.64810888e-46, 1.01370173e-50,
        2.23232813e-56, 6.05405202e-54, 1.15990266e-03]))

In [51]:
from sklearn.feature_selection import SelectKBest,mutual_info_classif
X,y = (df_packet_unique.drop(['proto','label'],1),df_packet_unique['label'].astype('int'))
print(X.head())
SelectKBest(mutual_info_classif,k='all').fit(X,y).score_func(X,y)

    smallpacket  packetratio  initlen   Botresp   outavglen    inavglen  \
1             3     0.411765       48  0.708333  519.411765  611.571429   
2             4     0.739130       48  0.575000  567.956522  519.411765   
3             3     0.363636       48  0.733333  195.272727  177.750000   
4             4     0.785714       48  0.560000  200.785714  195.272727   
34            2     0.875000       53  0.533333   50.375000   96.571429   

    averagelen      outvarlen       invarlen      totavglen  noofpackets  
1   546.291667  400162.830450  445105.102041  415025.706597           24  
2   547.325000  421805.519849  400162.830450  413183.269375           40  
3   190.600000   89316.743802   54753.187500   80159.840000           15  
4   198.360000   84329.311224   89316.743802   86531.270400           25  
34   71.933333      48.234375   26062.530612   12719.395556           15  


array([0.09606969, 0.1477355 , 0.06148472, 0.13902832, 0.09924388,
       0.09537341, 0.00608878, 0.05875191, 0.0686598 , 0.01781257,
       0.04173501])

In [65]:
df_corr = df_packet_unique.drop(['proto','smallpacket','initlen'],1)

In [66]:
from sklearn.preprocessing import RobustScaler
transformer = RobustScaler().fit(df_packet_unique.drop(['label','proto'],1))

In [67]:
X_scaled = transformer.transform(df_packet_unique.drop(['label','proto'],1))

In [74]:
df_scaled = pd.DataFrame(X_scaled,columns=['smallpacket', 'packetratio', 'initlen', 'Botresp',
       'outavglen', 'inavglen', 'averagelen', 'outvarlen', 'invarlen',
       'totavglen', 'noofpackets'])

In [77]:
df_scaled['proto'] = df_packet_unique['proto'].tolist()

In [79]:
df_scaled.shape

(4652, 12)

In [131]:
import numpy as np
from sklearn.decomposition import PCA
pca = PCA()
pca.fit(df_scaled) 

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [132]:
[float(i) for i  in pca.explained_variance_ratio_]

[0.49159820004795074,
 0.45019774098156756,
 0.04328231487334353,
 0.011753499650765083,
 0.0014693601923546542,
 0.0011282570446739353,
 0.0002470934851413441,
 0.00014310386694622464,
 9.434753032809346e-05,
 7.135824608635833e-05,
 1.3714823319456046e-05,
 1.0092575231359365e-06]

In [133]:
df_pca = pca.transform(df_scaled)

In [134]:
df_pca = pd.DataFrame(df_pca)
df_pca['label'] = df_packet_unique['label'].tolist()
df_pca.head()

0         1         2         3         4         5         6  \
0 -11.292449 -5.195448 -1.475464  8.291661  2.375845 -0.579929  1.389391   
1 -11.320162 -4.720752 -1.423339  8.088882  2.109965  0.306171  1.011572   
2 -11.228326 -5.494497 -1.258989  5.511610 -3.454725 -0.793809  0.145674   
3 -11.248849 -5.183582 -1.184954  5.551883 -3.144755  0.383480  0.436422   
4  -6.003960 -5.369695 -0.969146 -4.826959  0.385634 -0.239466  0.278064   

          7         8         9        10        11  label  
0  0.041358  0.496893 -0.159119 -0.166070 -0.034888      1  
1 -0.471276  0.082157 -0.484408 -0.195736 -0.001905      0  
2 -0.193860  0.469909  0.072794  0.034289  0.021225      1  
3 -0.032049 -0.126291 -0.169744  0.090690  0.005130      0  
4  0.142111 -0.200029 -0.175093 -0.045592 -0.001179      1

In [135]:
df_pca.to_csv('df_pca.csv',index=False)

In [136]:
from sklearn.metrics import classification_report,confusion_matrix
def ml(df,clf):
    X_train,X_test,y_train,y_test = train_test_split(df.drop(['label'],1),df['label'],test_size=0.3,random_state=123)
    clf.fit(X_train,y_train)
    print(y_train.value_counts())
    print(y_test.value_counts())
    pred = clf.predict(X_test)
    print(confusion_matrix(y_test,pred))
    print(classification_report(y_test,pred))

In [137]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(50,40),verbose=True,random_state=123)
ml(df_pca,mlp)

Iteration 1, loss = 0.88618750
Iteration 2, loss = 0.58037264
Iteration 3, loss = 0.51970341
Iteration 4, loss = 0.48883856
Iteration 5, loss = 0.47216467
Iteration 6, loss = 0.45667330
Iteration 7, loss = 0.44123921
Iteration 8, loss = 0.43152788
Iteration 9, loss = 0.42361815
Iteration 10, loss = 0.41143097
Iteration 11, loss = 0.40026174
Iteration 12, loss = 0.39096061
Iteration 13, loss = 0.38378987
Iteration 14, loss = 0.37634802
Iteration 15, loss = 0.36774452
Iteration 16, loss = 0.36098194
Iteration 17, loss = 0.35385151
Iteration 18, loss = 0.34997078
Iteration 19, loss = 0.34312756
Iteration 20, loss = 0.33757265
Iteration 21, loss = 0.33079502
Iteration 22, loss = 0.33028397
Iteration 23, loss = 0.33639790
Iteration 24, loss = 0.32469975
Iteration 25, loss = 0.31502098
Iteration 26, loss = 0.31392890
Iteration 27, loss = 0.31256748
Iteration 28, loss = 0.31148313
Iteration 29, loss = 0.30578087
Iteration 30, loss = 0.30639467
Iteration 31, loss = 0.30471369
Iteration 32, los

/home/shreyas/.local/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [138]:
df_pca.iloc[:,:3].head()

0         1         2
0 -11.292449 -5.195448 -1.475464
1 -11.320162 -4.720752 -1.423339
2 -11.228326 -5.494497 -1.258989
3 -11.248849 -5.183582 -1.184954
4  -6.003960 -5.369695 -0.969146

In [139]:
mlp = MLPClassifier(hidden_layer_sizes=(50,40),verbose=True,random_state=123)
df_dash = df_pca.iloc[:,:3]
df_dash['label'] = df_packet_unique['label'].tolist()
ml(df_dash,mlp)

/home/shreyas/.local/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


Iteration 1, loss = 0.61477705
Iteration 2, loss = 0.56431743
Iteration 3, loss = 0.54690267
Iteration 4, loss = 0.54324153
Iteration 5, loss = 0.53693887
Iteration 6, loss = 0.53633936
Iteration 7, loss = 0.52726351
Iteration 8, loss = 0.52315757
Iteration 9, loss = 0.51881606
Iteration 10, loss = 0.51878910
Iteration 11, loss = 0.51415962
Iteration 12, loss = 0.52352760
Iteration 13, loss = 0.51752408
Iteration 14, loss = 0.50803876
Iteration 15, loss = 0.50452647
Iteration 16, loss = 0.50306751
Iteration 17, loss = 0.50156187
Iteration 18, loss = 0.50274075
Iteration 19, loss = 0.49882675
Iteration 20, loss = 0.49492352
Iteration 21, loss = 0.49476818
Iteration 22, loss = 0.49067797
Iteration 23, loss = 0.48997534
Iteration 24, loss = 0.49319827
Iteration 25, loss = 0.48621206
Iteration 26, loss = 0.48598971
Iteration 27, loss = 0.48025482
Iteration 28, loss = 0.48393503
Iteration 29, loss = 0.48015152
Iteration 30, loss = 0.48458576
Iteration 31, loss = 0.47618201
Iteration 32, los

In [113]:
mlp = MLPClassifier(hidden_layer_sizes=(50,40),verbose=True,random_state=123)
df_dash = df_pca.iloc[:,:6]
df_dash['label'] = df_packet_unique['label'].tolist()
ml(df_dash,mlp)

/home/shreyas/.local/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


Iteration 1, loss = 0.65052384
Iteration 2, loss = 0.54395202
Iteration 3, loss = 0.50263315
Iteration 4, loss = 0.48447845
Iteration 5, loss = 0.47141852
Iteration 6, loss = 0.45906947
Iteration 7, loss = 0.44309405
Iteration 8, loss = 0.43294667
Iteration 9, loss = 0.42256740
Iteration 10, loss = 0.41702830
Iteration 11, loss = 0.41096332
Iteration 12, loss = 0.40404153
Iteration 13, loss = 0.40505768
Iteration 14, loss = 0.39359952
Iteration 15, loss = 0.38416218
Iteration 16, loss = 0.38004896
Iteration 17, loss = 0.38353075
Iteration 18, loss = 0.37288173
Iteration 19, loss = 0.37055048
Iteration 20, loss = 0.36774994
Iteration 21, loss = 0.36279388
Iteration 22, loss = 0.35813734
Iteration 23, loss = 0.36640607
Iteration 24, loss = 0.36115557
Iteration 25, loss = 0.36569833
Iteration 26, loss = 0.37974263
Iteration 27, loss = 0.35470658
Iteration 28, loss = 0.36025485
Iteration 29, loss = 0.36549939
Iteration 30, loss = 0.35283535
Iteration 31, loss = 0.34327765
Iteration 32, los

In [118]:
mlp = MLPClassifier(hidden_layer_sizes=(50,40),verbose=True,random_state=123)
df_dash = df_pca.iloc[:,:6]
df_dash['label'] = df_packet_unique['label'].tolist()
ml(df_dash,mlp)

/home/shreyas/.local/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


Iteration 1, loss = 0.65052384
Iteration 2, loss = 0.54395202
Iteration 3, loss = 0.50263315
Iteration 4, loss = 0.48447845
Iteration 5, loss = 0.47141852
Iteration 6, loss = 0.45906947
Iteration 7, loss = 0.44309405
Iteration 8, loss = 0.43294667
Iteration 9, loss = 0.42256740
Iteration 10, loss = 0.41702830
Iteration 11, loss = 0.41096332
Iteration 12, loss = 0.40404153
Iteration 13, loss = 0.40505768
Iteration 14, loss = 0.39359952
Iteration 15, loss = 0.38416218
Iteration 16, loss = 0.38004896
Iteration 17, loss = 0.38353075
Iteration 18, loss = 0.37288173
Iteration 19, loss = 0.37055048
Iteration 20, loss = 0.36774994
Iteration 21, loss = 0.36279388
Iteration 22, loss = 0.35813734
Iteration 23, loss = 0.36640607
Iteration 24, loss = 0.36115557
Iteration 25, loss = 0.36569833
Iteration 26, loss = 0.37974263
Iteration 27, loss = 0.35470658
Iteration 28, loss = 0.36025485
Iteration 29, loss = 0.36549939
Iteration 30, loss = 0.35283535
Iteration 31, loss = 0.34327765
Iteration 32, los

In [140]:
from sklearn.feature_selection import SelectKBest,mutual_info_classif
X,y = df_pca.drop(['label'],1),df_packet_unique['label'].astype('int')
kbest = SelectKBest(mutual_info_classif,k=4)
kbest = kbest.fit(X,y)
print(kbest.scores_)
# print(X.head())
X_new = kbest.transform(X)
X_new.shape

[0.05668629 0.06962147 0.06396576 0.08500622 0.04987894 0.15471182
 0.0824545  0.06487307 0.07154848 0.05577817 0.05010658 0.02681605]


(4652, 4)

In [141]:
df_kbest = pd.DataFrame(X_new)
df_kbest['label'] = df_packet_unique['label'].tolist()
mlp = MLPClassifier(hidden_layer_sizes=(50,40),verbose=True,random_state=456)
ml(df_kbest,mlp)

Iteration 1, loss = 0.60596832
Iteration 2, loss = 0.53530163
Iteration 3, loss = 0.51701451
Iteration 4, loss = 0.50963928
Iteration 5, loss = 0.50435716
Iteration 6, loss = 0.50119884
Iteration 7, loss = 0.49874966
Iteration 8, loss = 0.49587457
Iteration 9, loss = 0.49364445
Iteration 10, loss = 0.49082513
Iteration 11, loss = 0.48853130
Iteration 12, loss = 0.48714515
Iteration 13, loss = 0.48484280
Iteration 14, loss = 0.48256294
Iteration 15, loss = 0.48105649
Iteration 16, loss = 0.47959794
Iteration 17, loss = 0.47806057
Iteration 18, loss = 0.47526374
Iteration 19, loss = 0.47350288
Iteration 20, loss = 0.47155104
Iteration 21, loss = 0.46967488
Iteration 22, loss = 0.46776261
Iteration 23, loss = 0.46596378
Iteration 24, loss = 0.46641577
Iteration 25, loss = 0.46244076
Iteration 26, loss = 0.46224245
Iteration 27, loss = 0.45918796
Iteration 28, loss = 0.46182461
Iteration 29, loss = 0.45894031
Iteration 30, loss = 0.45716789
Iteration 31, loss = 0.45596707
Iteration 32, los

/home/shreyas/.local/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [ ]:
# PCA with Duplicates

In [146]:
df_packet.shape

(113288, 13)

In [149]:
df_X = df_packet.drop(['label','proto'],1)
y = df_packet['label']
print(y.shape)

(113288,)


In [147]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import RobustScaler

X_scaled = RobustScaler().fit_transform(df_X)
pca = PCA()
X_pca_scaled = pca.fit_transform(X_scaled)
X_pca_scaled.shape

(113288, 11)

In [150]:
df_pca_scaled = pd.DataFrame(X_pca_scaled)
print(df_pca_scaled.shape)
df_pca_scaled['label'] = y.tolist()
mlp = MLPClassifier(hidden_layer_sizes=(50,40),verbose=True,random_state=456)
ml(df_pca_scaled,mlp)

(113288, 11)
Iteration 1, loss = 0.23641642
Iteration 2, loss = 0.12424682
Iteration 3, loss = 0.10816828
Iteration 4, loss = 0.09921670
Iteration 5, loss = 0.09363497
Iteration 6, loss = 0.08811844
Iteration 7, loss = 0.08681024
Iteration 8, loss = 0.07899161
Iteration 9, loss = 0.07488594
Iteration 10, loss = 0.07071989
Iteration 11, loss = 0.06757763
Iteration 12, loss = 0.06546209
Iteration 13, loss = 0.06296986
Iteration 14, loss = 0.05991390
Iteration 15, loss = 0.05904049
Iteration 16, loss = 0.05746863
Iteration 17, loss = 0.05574387
Iteration 18, loss = 0.05389985
Iteration 19, loss = 0.05381380
Iteration 20, loss = 0.05181183
Iteration 21, loss = 0.05061174
Iteration 22, loss = 0.04971967
Iteration 23, loss = 0.04941409
Iteration 24, loss = 0.04940591
Iteration 25, loss = 0.04761942
Iteration 26, loss = 0.04755875
Iteration 27, loss = 0.04689371
Iteration 28, loss = 0.04754220
Iteration 29, loss = 0.04648938
Iteration 30, loss = 0.04501991
Iteration 31, loss = 0.04529597
Iter

In [ ]:
#                           precision  recall     f1       
# After pca all             0.89      0.90      0.89   
# pca only first 3          0.76      0.78      0.75
# pca after first 6         0.87      0.87      0.87
# kbest 4 after pca         0.81      0.81      0.80 
# pca with duplicates       0.99      0.99      0.99 